// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddToLibrary'](arg1, arg2, arg3, arg4);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetAnnouncements() {
  return window['go']['main']['App']['GetAnnouncements']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetailedConfig() {
  return window['go']['main']['App']['GetDetailedConfig']();
}

export function GetGameDetail(arg1) {
  return window['go']['main']['App']['GetGameDetail'](arg1);
}

export function GetKernelSettings() {
  return window['go']['main']['App']['GetKernelSettings']();
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function LoadKernel() {
  return window['go']['main']['App']['LoadKernel']();
}

export function PatchVDF() {
  return window['go']['main']['App']['PatchVDF']();
}

export function RemoveFromLibrary(arg1) {
  return window['go']['main']['App']['RemoveFromLibrary'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RestartSteam() {
  return window['go']['main']['App']['RestartSteam']();
}

export function SearchStore(arg1) {
  return window['go']['main']['App']['SearchStore'](arg1);
}

export function SetKernelSettings(arg1) {
  return window['go']['main']['App']['SetKernelSettings'](arg1);
}

export function StartUnlock(arg1) {
  return window['go']['main']['App']['StartUnlock'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function VerifyKey(arg1) {
  return window['go']['main']['App']['VerifyKey'](arg1);
}
