// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConfig():Promise<models.ConfigResponse>;

export function GetDetailedConfig():Promise<models.DetailedConfigResponse>;

export function GetTaskStatus():Promise<models.TaskStatusResponse>;

export function ResetConfig():Promise<models.SimpleResponse>;

export function StartUnlock(arg1:string,arg2:boolean):Promise<models.SimpleResponse>;

export function UpdateConfig(arg1:models.UpdateConfigRequest):Promise<models.SimpleResponse>;

export function VerifyKey(arg1:string):Promise<models.KeyInfoAPIResponse>;
