// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetailedConfig() {
  return window['go']['main']['App']['GetDetailedConfig']();
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function StartUnlock(arg1, arg2) {
  return window['go']['main']['App']['StartUnlock'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function VerifyKey(arg1) {
  return window['go']['main']['App']['VerifyKey'](arg1);
}
