// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddToLibrary(arg1:number,arg2:string,arg3:string,arg4:string):Promise<models.SimpleResponse>;

export function CheckUpdate():Promise<models.UpdateInfo>;

export function GetAnnouncements():Promise<models.AnnouncementResponse>;

export function GetConfig():Promise<models.ConfigResponse>;

export function GetDetailedConfig():Promise<models.DetailedConfigResponse>;

export function GetGameDetail(arg1:number):Promise<models.LibraryGame>;

export function GetKernelSettings():Promise<models.KernelSettingsResponse>;

export function GetLibrary():Promise<Array<models.LibraryGame>>;

export function GetTaskStatus():Promise<models.TaskStatusResponse>;

export function LoadKernel():Promise<models.SimpleResponse>;

export function PatchVDF():Promise<models.SimpleResponse>;

export function RemoveFromLibrary(arg1:number):Promise<models.SimpleResponse>;

export function ResetConfig():Promise<models.SimpleResponse>;

export function RestartSteam():Promise<models.SimpleResponse>;

export function SearchStore(arg1:string):Promise<models.StoreSearchResult>;

export function SetKernelSettings(arg1:models.KernelSettings):Promise<models.SimpleResponse>;

export function StartUnlock(arg1:string):Promise<models.SimpleResponse>;

export function UpdateConfig(arg1:models.UpdateConfigRequest):Promise<models.SimpleResponse>;

export function VerifyKey(arg1:string):Promise<models.KeyInfoAPIResponse>;
