name: DEV Test Build

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 安装 Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 安装 Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: 获取版本
        shell: powershell
        run: |
          $wailsJson = Get-Content wails.json | ConvertFrom-Json
          $version = $wailsJson.info.productVersion
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV

      - name: 编译
        run: wails build -o "Onekey_v${{ env.PACKAGE_VERSION }}.exe" -upx -skipbindings

      - name: 上传包
        uses: actions/upload-artifact@v4
        with:
          name: Onekey_v${{ env.PACKAGE_VERSION }}.exe
          path: build/bin/Onekey_v${{ env.PACKAGE_VERSION }}.exe
